#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>
#include <algorithm>

static const char emitter_hpp[] = {
#embed "uniqtype_emit.hpp"
};
static const char discover_cpp[] = {
#embed "discover.cpp"
};
static const char codeful_hpp[] = {
#embed "srctypes_codeful.hpp"
};
static const char version_script[] = {
#embed "meta.map"
};

static std::string env_or(const char *key, const char *dflt)
{
    const char *v = std::getenv(key);
    return (v && *v) ? std::string(v) : std::string(dflt);
}

static std::string chomp(std::string s)
{
    while (!s.empty() && (s.back() == '\n' || s.back() == '\r')) s.pop_back();
    return s;
}

static std::string popen_line(const std::string &cmd)
{
    FILE *p = popen(cmd.c_str(), "r");
    if (!p) return {};
    char buf[4096];
    std::string r = std::fgets(buf, sizeof buf, p) ? chomp(buf) : std::string();
    pclose(p);
    return r;
}

static std::string abspath(const std::string &p)
{
    std::string r = popen_line("readlink -f '" + p + "' 2>/dev/null");
    return r.empty() ? p : r;
}

static std::string dirname_of(const std::string &p)
{
    std::string::size_type slash = p.find_last_of('/');
    return slash == std::string::npos ? std::string(".") : p.substr(0, slash);
}

static void shell_ignore(const std::string &cmd)
{
    int rc = std::system(cmd.c_str());
    (void) rc;
}

static void cleanup_tmp(const std::string &tmp)
{
    if (std::getenv("SRCTYPES_KEEP_TMP"))
        std::fprintf(stderr, "gen_meta: kept temp dir %s\n", tmp.c_str());
    else
        shell_ignore("rm -rf " + tmp);
}

static std::string make_tmpdir()
{
    return popen_line("mktemp -d 2>/dev/null");
}

static bool write_file(const std::string &path, const char *data, std::size_t n)
{
    FILE *f = std::fopen(path.c_str(), "wb");
    if (!f) { std::perror(("gen_meta: " + path).c_str()); return false; }
    bool ok = std::fwrite(data, 1, n, f) == n;
    std::fclose(f);
    return ok;
}

static std::string build_inputs_header(const std::vector<std::string> &inputs,
                                        const std::vector<std::string> &dirs)
{
    std::string s = "// Generated by gen_meta -- do not edit.\n";
    s += "#include <string_view>\n";
    for (auto &in : inputs) s += "#include \"" + in + "\"\n";
    s += "inline constexpr std::string_view srctypes_input_dirs[] = {\n";
    for (auto &d : dirs) s += "  \"" + d + "/\",\n";
    s += "};\n";
    return s;
}

static std::string build_tu(const std::vector<std::string> &name,
                            const std::vector<long> &nrel)
{
    std::string s;
    s += "// Generated by gen_meta -- do not edit.\n";
    s += "#define HELLO_FROM_GENMETA\n";
    s.append(emitter_hpp, sizeof emitter_hpp);
    s += "\n";
    
    // I had a chat with Herb Sutter a year ago, they want something that will take care of this in C++29
    s += "// One canonical, externally-named object per discovered uniqtype,\n";
    s += "// sized for the header plus its related[] entries.\n";
    s += "extern \"C\" {\n";
    for (std::size_t i = 0; i < name.size(); ++i) {
        std::string n = std::to_string(nrel[i]);
        s += "  alignas(uniqtype) unsigned char __uniqtype__" + name[i] +
             "[sizeof(uniqtype) + (" + n + " ? " + n + " : 1) * sizeof(uniqtype_rel_info)] = {};\n";
    }
    s += "}\n\n";

    s += "// Storage hook: the emitter routes every emit() through here, so each\n";
    s += "// type's exported object and all references to it are one and the same.\n";
    s += "extern \"C\" uniqtype *__srctypes_canonical_storage(const char *codeful) {\n";
    for (std::size_t i = 0; i < name.size(); ++i)
        s += "  if (!__builtin_strcmp(codeful, \"" + name[i] + "\")) "
             "return reinterpret_cast<uniqtype *>(__uniqtype__" + name[i] + ");\n";
    s += "  return (uniqtype *) 0;\n";
    s += "}\n";
    return s;
}

int main(int argc, char **argv)
{
    bool dump = false;
    std::string out_so;
    std::vector<std::string> inputs;
    for (int i = 1; i < argc; ++i) {
        std::string a = argv[i];
        if (a == "--dump") dump = true;
        else if (a == "-o") { if (i + 1 < argc) out_so = argv[++i]; }
        else inputs.push_back(a);
    }
    if (inputs.empty()) {
        std::fprintf(stderr, "usage: %s [--dump] [-o out.so] <input>...\n", argv[0]);
        return 2;
    }
    if (out_so.empty()) dump = true;   // nothing to build -> just show the TU

    std::vector<std::string> dirs;
    for (auto &in : inputs) {
        in = abspath(in);
        std::string d = dirname_of(in);
        if (std::find(dirs.begin(), dirs.end(), d) == dirs.end()) dirs.push_back(d);
    }

    const std::string cxx      = env_or("SRCTYPES_CXX", "g++-16");
    const std::string cxxflags = env_or("SRCTYPES_CXXFLAGS", "-std=c++26 -freflection");

    std::string tmp = make_tmpdir();
    if (tmp.empty()) {
        std::fprintf(stderr, "gen_meta: could not create a temp directory\n");
        return 1;
    }
    const std::string disc_src = tmp + "/discover.cpp";
    const std::string disc_bin = tmp + "/discover";

    std::string inputs_hpp = build_inputs_header(inputs, dirs);
    if (!write_file(tmp + "/srctypes_codeful.hpp", codeful_hpp, sizeof codeful_hpp) ||
        !write_file(tmp + "/srctypes_inputs.hpp", inputs_hpp.data(), inputs_hpp.size()) ||
        !write_file(disc_src, discover_cpp, sizeof discover_cpp)) {
        cleanup_tmp(tmp);
        return 1;
    }

    // PASS 1: compile+run discovery. --unresolved-symbols=ignore-all lets the
    // discovery binary link even when the included library code references
    // symbols it never calls during reflection.
    std::string compile = cxx + " " + cxxflags +
        " -Wl,--unresolved-symbols=ignore-all " + disc_src + " -o " + disc_bin;
    if (int rc = std::system(compile.c_str())) {
        std::fprintf(stderr, "gen_meta: failed to compile discovery program (status %d):\n  %s\n",
                     rc, compile.c_str());
        cleanup_tmp(tmp);
        return 1;
    }

    std::vector<std::string> name;
    std::vector<long>        nrel;
    FILE *p = popen(disc_bin.c_str(), "r");
    if (!p) {
        std::perror("gen_meta: popen");
        cleanup_tmp(tmp);
        return 1;
    }
    char line[8192];
    while (std::fgets(line, sizeof line, p)) {
        std::string s = chomp(line);
        if (s.empty()) continue;
        std::string::size_type tab = s.find('\t');
        if (tab == std::string::npos) {
            std::fprintf(stderr, "gen_meta: malformed discover line: %s\n", s.c_str());
            pclose(p);
            cleanup_tmp(tmp);
            return 1;
        }
        name.push_back(s.substr(0, tab));
        nrel.push_back(std::strtol(s.c_str() + tab + 1, nullptr, 10));
    }
    if (int run_rc = pclose(p)) {
        std::fprintf(stderr, "gen_meta: discovery program failed (status %d)\n", run_rc);
        cleanup_tmp(tmp);
        return 1;
    }

    // PASS 2: assemble the meta TU.
    std::string tu = build_tu(name, nrel);

    if (dump)
        std::fwrite(tu.data(), 1, tu.size(), stdout);

    int status = 0;
    if (!out_so.empty()) {
        // PASS 3: compile the meta TU into the meta-DSO, exporting only the
        // uniqtype objects via the version script.
        const std::string tu_path  = tmp + "/meta.gen.cpp";
        const std::string map_path = tmp + "/meta.map";
        if (write_file(tu_path, tu.data(), tu.size()) &&
            write_file(map_path, version_script, sizeof version_script)) {
            std::string link = cxx + " " + cxxflags + " -shared -Wl,--version-script=" +
                map_path + " -Wl,--unresolved-symbols=ignore-all " + tu_path + " -o " + out_so;
            if (int rc = std::system(link.c_str())) {
                std::fprintf(stderr, "gen_meta: failed to link meta-DSO (status %d):\n  %s\n",
                             rc, link.c_str());
                status = 1;
            }
        } else {
            status = 1;
        }
    }

    cleanup_tmp(tmp);
    return status;
}
