#ifndef HELLO_FROM_GENMETA
#error "This header is junk without it's generated tail: never include it."
#endif

#include <meta>
#include <type_traits>
#include <cstddef>
#include <cstdio>
#include <cstdlib>

extern "C" {
#include "uniqtype-defs.h"
}

#include "srctypes_inputs.hpp" // Generated by the driver
#include "srctypes_codeful.hpp"
#include "srctypes_subrange.hpp"


namespace sm = std::meta;

// DWARF base-type encodings (DW_ATE_*)
enum : unsigned {
    DW_ATE_boolean       = 0x02,
    DW_ATE_float         = 0x04,
    DW_ATE_signed        = 0x05,
    DW_ATE_signed_char   = 0x06,
    DW_ATE_unsigned      = 0x07,
    DW_ATE_unsigned_char = 0x08,
    DW_ATE_UTF           = 0x10,
};

template <typename T>
consteval unsigned base_encoding() {
    using U = std::remove_cv_t<T>;
    if constexpr (std::is_same_v<U, bool>)               return DW_ATE_boolean;
    else if constexpr (std::is_same_v<U, char>)          return std::is_signed_v<char> ? DW_ATE_signed_char : DW_ATE_unsigned_char;
    else if constexpr (std::is_same_v<U, signed char>)   return DW_ATE_signed_char;
    else if constexpr (std::is_same_v<U, unsigned char>) return DW_ATE_unsigned_char;
    else if constexpr (std::is_same_v<U, char8_t> ||
                       std::is_same_v<U, char16_t> ||
                       std::is_same_v<U, char32_t>)       return DW_ATE_UTF;
    else if constexpr (std::is_same_v<U, wchar_t>)        return std::is_signed_v<wchar_t> ? DW_ATE_signed : DW_ATE_unsigned;
    else if constexpr (std::is_floating_point_v<U>)       return DW_ATE_float;
    else if constexpr (std::is_integral_v<U>)             return std::is_signed_v<U> ? DW_ATE_signed : DW_ATE_unsigned;
    else static_assert(sizeof(T) == 0, "not a base type");
}

template <typename T>
consteval std::string_view uniqtype_symbol() {
    return std::define_static_string("__uniqtype__" + codeful_name<T>());
}

// ---------------------------------------------------------------------------
// Per-kind emitters.  Each returns a pointer to a static uniqtype with the
// canonical external symbol attached.
// ---------------------------------------------------------------------------
template <typename T> const uniqtype *emit(); 

// ---------------------------------------------------------------------------
// Canonical storage lookup.
//
// Every emitted uniqtype lives in the external, canonically-named
// __uniqtype__<codeful> object that liballocs looks up. The driver's generated
// tail declares one such object per discovered type. We unfortunately can't declare
// them with the available reflection tooling just yet.
//
// ---------------------------------------------------------------------------
extern "C" uniqtype *__srctypes_canonical_storage(const char *codeful);

template <typename T>
uniqtype *canonical() {
    static constexpr const char *nm = std::define_static_string(codeful_name<T>());
    if (uniqtype *ext = __srctypes_canonical_storage(nm)) return ext;
    std::fprintf(stderr,
        "srctypes: emitter/discover closure mismatch: no canonical storage "
        "declared for type \"%s\"\n", nm);
    std::abort();
}

template <typename T>
const uniqtype *emit_base() {
    uniqtype *t = canonical<T>();
    static bool done = false;
    if (done) return t;
    done = true;
    t->pos_maxoff   = sizeof(T);
    t->un.info.kind = BASE;
    t->un.base.enc  = base_encoding<T>();
    return t;
}

template <typename Pointee>
const uniqtype *emit_address() {
    // related[0] is the immediate pointee; for a multi-level pointer (indir_level
    // > 1) related[1] is the ultimate non-pointer pointee (per
    // UNIQTYPE_ULTIMATE_POINTEE_TYPE).
    constexpr unsigned indir = 1 + ptr_depth_v<Pointee>;
    uniqtype *t = canonical<Pointee *>();
    // `done` is set true *before* recursing into the pointee, so a self-
    // referential type does not trigger recursive static init error
    static bool done = false;
    if (done) return t;
    done = true;
    t->pos_maxoff             = sizeof(void *);
    t->un.info.kind           = ADDRESS;
    t->un.address.indir_level = indir;
    t->related[0].un.t.ptr    = const_cast<uniqtype *>(emit<Pointee>());
    if constexpr (indir > 1)
        t->related[1].un.t.ptr = const_cast<uniqtype *>(emit<remove_all_ptr_t<Pointee>>());
    return t;
}

template <typename Elem>
const uniqtype *emit_array_unbounded() {
    uniqtype *t = canonical<Elem[]>();
    static bool done = false;
    if (done) return t;
    done = true;
    t->pos_maxoff      = UNIQTYPE_POS_MAXOFF_UNBOUNDED;
    t->un.info.kind    = ARRAY;
    t->un.array.nelems = UNIQTYPE_ARRAY_LENGTH_UNBOUNDED;
    t->related[0].un.t.ptr = const_cast<uniqtype *>(emit<Elem>());
    return t;
}

template <typename T = void>
const uniqtype *emit_void() {
    return &__uniqtype__void;
}

template <typename Elem, std::size_t N>
const uniqtype *emit_array() {
    uniqtype *t = canonical<Elem[N]>();
    static bool done = false;
    if (done) return t;
    done = true;
    t->pos_maxoff      = sizeof(Elem) * N;
    t->un.info.kind    = ARRAY;
    t->un.array.nelems = N;
    t->related[0].un.t.ptr = const_cast<uniqtype *>(emit<Elem>());
    return t;
}

template <typename T>
const uniqtype *emit_subrange() {
    using ST = subrange_traits<T>;
    uniqtype *t = canonical<T>();
    static bool done = false;
    if (done) return t;
    done = true;
    t->pos_maxoff       = sizeof(typename ST::host);
    t->un.info.kind     = SUBRANGE;
    t->un.subrange.min  = (unsigned) ST::min;       // 14-bit fields
    t->un.subrange.max  = (unsigned) ST::max;
    t->related[0].un.t.ptr = const_cast<uniqtype *>(emit<typename ST::host>());
    return t;
}

template <typename E>
const uniqtype *emit_enumeration() {
    // related[0] is the underlying base type (per UNIQTYPE_ENUM_BASE_TYPE);
    // related[1..nenum] carry the enumerator values.
    static constexpr auto enums = std::define_static_array(sm::enumerators_of(^^E));
    constexpr std::size_t nenum = enums.size();
    uniqtype *t = canonical<E>();
    static bool done = false;
    if (done) return t;
    done = true;
    t->pos_maxoff           = sizeof(E);
    t->un.info.kind         = ENUMERATION;
    t->un.enumeration.nenum = nenum;
    t->related[0].un.t.ptr  = const_cast<uniqtype *>(emit<std::underlying_type_t<E>>());
    std::size_t i = 1;
    template for (constexpr auto e : enums) {
        constexpr E val = sm::extract<E>(e);
        t->related[i++].un.enumerator.val =
            (unsigned long) static_cast<std::underlying_type_t<E>>(val);
    }
    return t;
}

// A bit-field gets a member-local, NON-canonical base type: its codeful name
// would clash, so it is never routed through canonical() or exported -- it lives
// in a magic static buffer instead.
template <typename Under, unsigned BitSize, unsigned ByteSize, int BitOff>
const uniqtype *emit_bitfield_base() {
    alignas(uniqtype) [[gnu::used]] static unsigned char storage[sizeof(uniqtype)] = {};
    uniqtype *t = reinterpret_cast<uniqtype *>(&storage[0]);
    static bool done = false;
    if (done) return t;
    done = true;
    t->pos_maxoff   = ByteSize;
    t->un.info.kind = BASE;
    t->un.base.enc  = base_encoding<Under>();
    // bit_size_delta = 8*ByteSize - BitSize, split into a power-of-two part
    // (one_plus_log_bit_size_delta) and a signed remainder (bit_size_delta_delta).
    signed delta = (signed)(8 * ByteSize) - (signed) BitSize;
    if (delta) {
        unsigned ord   = 31u - (unsigned) __builtin_clz((unsigned) delta);
        signed   lower = delta - (signed)(1u << ord);
        if (lower < 128) {
            t->un.base.one_plus_log_bit_size_delta = 1 + ord;
            t->un.base.bit_size_delta_delta        = lower;
        } else {
            t->un.base.one_plus_log_bit_size_delta = 2 + ord;
            t->un.base.bit_size_delta_delta        = delta - (signed)(1u << (ord + 1));
        }
    }
    t->un.base.bit_off = BitOff;
    return t;
}

template <typename T>
const uniqtype *emit_composite() {
    // `members` must have a constant address to drive `template for`, hence static.
    static constexpr auto members = std::define_static_array(
        sm::nonstatic_data_members_of(^^T, sm::access_context::current()));
    constexpr std::size_t nmemb = members.size();

    // related[0..nmemb-1] are the members; related[nmemb] holds the member-names
    // vector (per UNIQTYPE_COMPOSITE_SUBOBJ_NAMES). discover.cpp sizes the
    // canonical object for all nmemb+1 entries.
    uniqtype *t = canonical<T>();
    // Set `done` before wiring members so that a member type which refers back
    // to T (directly or via a pointer) re-enters emit<T>() and receives this
    // stable address rather than recursively re-initialising it.
    static bool done = false;
    if (done) return t;
    done = true;
    t->pos_maxoff                    = sizeof(T);
    t->un.info.kind                  = COMPOSITE;
    t->un.composite.nmemb            = nmemb;
    // a union's members all occupy the same storage, so at most one is valid
    t->un.composite.not_simultaneous = std::is_union_v<T> ? 1 : 0;

    // Names vector, pointed to from related[nmemb].
    [[gnu::used]] static const char *names[nmemb ? nmemb : 1] = {};

    std::size_t i = 0;
    template for (constexpr auto m : members) {
        using MT = typename [: sm::type_of(m) :];
        constexpr auto off = sm::offset_of(m);
        constexpr const char *nm = sm::has_identifier(m)
            ? std::define_static_string(std::string(sm::identifier_of(m))) : "";
        t->related[i].un.memb.off = off.bytes;
        if constexpr (sm::is_bit_field(m))
            t->related[i].un.memb.ptr = const_cast<uniqtype *>(
                emit_bitfield_base<std::remove_cv_t<MT>, (unsigned) sm::bit_size_of(m),
                                   (unsigned) sizeof(MT), (int) off.bits>());
        else
            t->related[i].un.memb.ptr = const_cast<uniqtype *>(emit<MT>());
        names[i] = nm;
        ++i;
    }
    t->related[nmemb].un.memb_names.n = names;
    return t;
}

// A SUBPROGRAM uniqtype: related[0] is the return type, related[1..narg] the
// argument types (matching uniqtype-defs.h). Specialised on the function type so
// the parameter pack is available; the codeful name comes from fn_codeful.
template <typename F> struct subprogram_emitter;
template <typename R, typename... A>
struct subprogram_emitter<R(A...)> {
    static const uniqtype *go() {
        uniqtype *t = canonical<R(A...)>();
        static bool done = false;
        if (done) return t;
        done = true;
        t->pos_maxoff          = 0;                  // function types have no size
        t->un.info.kind        = SUBPROGRAM;
        t->un.subprogram.narg  = sizeof...(A);
        t->un.subprogram.nret  = 1;                  // C/C++ single return (void => null)
        t->un.subprogram.is_va = 0;
        t->un.subprogram.cc    = 0;
        t->related[0].un.t.ptr = const_cast<uniqtype *>(emit<R>());
        std::size_t i = 1;
        ((t->related[i++].un.t.ptr = const_cast<uniqtype *>(emit<A>())), ...);
        return t;
    }
};
template <typename R, typename... A>
struct subprogram_emitter<R(A..., ...)> {            // variadic
    static const uniqtype *go() {
        uniqtype *t = canonical<R(A..., ...)>();
        static bool done = false;
        if (done) return t;
        done = true;
        t->pos_maxoff          = 0;
        t->un.info.kind        = SUBPROGRAM;
        t->un.subprogram.narg  = sizeof...(A);
        t->un.subprogram.nret  = 1;
        t->un.subprogram.is_va = 1;
        t->un.subprogram.cc    = 0;
        t->related[0].un.t.ptr = const_cast<uniqtype *>(emit<R>());
        std::size_t i = 1;
        ((t->related[i++].un.t.ptr = const_cast<uniqtype *>(emit<A>())), ...);
        return t;
    }
};

template <typename T>
const uniqtype *emit() {
    using U = std::remove_cv_t<T>;
    if constexpr (std::is_pointer_v<U>)
        return emit_address<std::remove_pointer_t<U>>();
    else if constexpr (std::is_unbounded_array_v<U>)
        return emit_array_unbounded<std::remove_extent_t<U>>();
    else if constexpr (std::is_array_v<U>)
        return emit_array<std::remove_extent_t<U>, std::extent_v<U>>();
    else if constexpr (std::is_function_v<U>)
        return subprogram_emitter<U>::go();
    else if constexpr (subrange_traits<U>::is)
        return emit_subrange<U>();
    else if constexpr (std::is_class_v<U> || std::is_union_v<U>)
        return emit_composite<U>();
    else if constexpr (std::is_arithmetic_v<U>)
        return emit_base<U>();
    else if constexpr (std::is_enum_v<U>)
        return emit_enumeration<U>();
    else if constexpr (std::is_void_v<U>)
        return emit_void();
    else
        static_assert(sizeof(T) == 0, "unhandled type kind");
}

namespace {

// Force-emit every library type
[[gnu::used]] const int _force_all = []{
    for_each_emittable_input_type([]<typename T>{ (void) emit<T>(); });
    return 0;
}();

} // namespace

// The driver appends the generated alias tail below this line.
