name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install -y \
            build-essential libbsd-dev libelf-dev libdw-dev binutils-dev \
            autoconf automake libtool pkg-config autoconf-archive \
            g++ ocaml ocamlbuild ocaml-findlib libnum-ocaml-dev \
            default-jdk-headless python3 \
            make git gawk gdb wget \
            libunwind-dev libc6-dev-i386 zlib1g-dev libc6-dbg \
            libboost-iostreams-dev libboost-regex-dev \
            libboost-serialization-dev libboost-filesystem-dev libffi-dev

      - name: Report OCaml version
        run: dpkg -l | grep ocaml

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build submodules
        run: make -C contrib -j 2

      - name: Build project
        run: |
          . contrib/env.sh
          ./autogen.sh
          ./configure
          make -j 2

      - name: Create liballocs metadata
        timeout-minutes: 25
        run: |
          sudo mkdir -p /usr/lib/meta && \
          sudo make -f tools/Makefile.meta \
              $(for libname in `ldd /bin/true | sed -En '/[[:blank:]]*([^[:blank:]]* => )?(.*) \(0x[0-9a-f]+\)/ {s//\2/;p}' | egrep 'libc\.so\.6|ld-linux.*\.so' | xargs readlink -f`; do echo "/usr/lib/meta${libname}-meta.so"; done)

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            /usr/lib/meta
            .

  test:
    needs: build
    runs-on: ubuntu-20.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install -y \
            ca-certificates make build-essential g++ autoconf automake libtool \
            libelf-dev python3 git gawk python3-distutils libunwind-dev \
            ocaml ocamlbuild ocaml-findlib \
            libdw-dev binutils-dev libffi-dev \
            libboost-iostreams-dev libboost-regex-dev \
            libboost-serialization-dev libboost-filesystem-dev

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: .

      - name: Run tests
        run: make -C tests -j 2 -k
